package com.shiptrack;

import com.shiptrack.dto.RegisterRequest;
import com.shiptrack.dto.UserDto;
import com.shiptrack.enums.Role;
import com.shiptrack.repository.UserRepository;
import com.shiptrack.service.UserService;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.transaction.annotation.Transactional;

import static org.junit.jupiter.api.Assertions.*;

@SpringBootTest
@Transactional
class UserServiceRegisterIdTest {

    @Autowired
    private UserService userService;

    @Autowired
    private UserRepository userRepository;

    @BeforeEach
    void setUp() {
        userRepository.deleteAll();
    }

    @Test
    void businessClientReceivesAutoGeneratedRegisterId() {
        RegisterRequest request = new RegisterRequest();
        request.setFullName("ABC Logistics");
        request.setEmail("abc-business@shiptrack.com");
        request.setPassword("password123");
        request.setConfirmPassword("password123");
        request.setRole(Role.BUSINESS_CLIENT);
        request.setPhoneNumber("9999999999");

        UserDto response = userService.registerUser(request);

        assertNotNull(response.getRegisterId(), "Business client should receive an auto-generated registerId");
        assertTrue(response.getRegisterId().startsWith("BUS-"), "registerId must follow the BUS-XXXXXXXX format");
        assertEquals(12, response.getRegisterId().length(), "registerId should be 'BUS-' plus an 8 character suffix");
    }

    @Test
    void nonBusinessClientRolesDoNotReceiveRegisterId() {
        RegisterRequest request = new RegisterRequest();
        request.setFullName("Regular Customer");
        request.setEmail("customer-noregid@shiptrack.com");
        request.setPassword("password123");
        request.setRole(Role.CUSTOMER);
        request.setPhoneNumber("8888888888");

        UserDto response = userService.registerUser(request);

        assertNull(response.getRegisterId(), "Only BUSINESS_CLIENT accounts should receive a registerId");
    }

    @Test
    void mismatchedConfirmPasswordIsRejected() {
        RegisterRequest request = new RegisterRequest();
        request.setFullName("Mismatch User");
        request.setEmail("mismatch@shiptrack.com");
        request.setPassword("password123");
        request.setConfirmPassword("differentPassword");
        request.setRole(Role.CUSTOMER);
        request.setPhoneNumber("7777777777");

        assertThrows(IllegalArgumentException.class, () -> userService.registerUser(request));
    }

    @Test
    void generatedRegisterIdsAreUniqueAcrossMultipleRegistrations() {
        for (int i = 0; i < 5; i++) {
            RegisterRequest request = new RegisterRequest();
            request.setFullName("Business " + i);
            request.setEmail("business" + i + "@shiptrack.com");
            request.setPassword("password123");
            request.setRole(Role.BUSINESS_CLIENT);
            request.setPhoneNumber("100000000" + i);
            userService.registerUser(request);
        }

        long distinctRegisterIds = userRepository.findAll().stream()
                .map(u -> u.getRegisterId())
                .filter(id -> id != null)
                .distinct()
                .count();

        assertEquals(5, distinctRegisterIds, "All generated registerIds must be unique");
    }
}
